name: Git Warp Time

on: [push]

jobs:

  gwt:
    runs-on: ubuntu-22.04
    name: Test GWT
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Confirm pre
        run: |
          ls -al
      - name: Git Warp Time
        uses: alerque/git-warp-time@latest
      - name: Confirm post
        run: |
          ls -al
